name: Pylint

on: [push]

jobs:
  check-modified:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for modified Python files
        id: check
        run: |
          if [ -n "$(git ls-files -m '*.py')" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  pylint:
    runs-on: ubuntu-latest
    needs: check-modified
    if: ${{ needs.check-modified.outputs.changed == 'true' }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing errors in the code with pylint
        run: |
          pylint -E $(git ls-files -m '*.py')
      - name: Analysing the code with pylint (non-fatal)
        run: |
          pylint --exit-zero $(git ls-files -m '*.py')
