name: Pylint

on: [push]

env:
  CHANGED

jobs:
  check-modified:
    outputs:
      changed: $CHANGED
    runs-on: ubuntu-latest
        run: |
          if [ -n "$(git ls-files -m '*.py')" ]; then
            echo "true" >> $CHANGED
          else
            echo "false" >> $CHANGED
          fi

  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    if: $CHANGED == 'true'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing errors the code with pylint
      run: |
        pylint -E $(git ls-files -m '*.py')
    - name: Analysing the code with pylint (non-fatal)
      run: |
        pylint --exit-zero $(git ls-files -m '*.py')
