name: Shellcheck

on: [push]

env:
  CHANGED: 'false'

jobs:
  check-modified:
    outputs:
      changed: $CHANGED
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ -n "$(git ls-files -m '*.sh')" ]; then
            echo 'true' >> $CHANGED
          else
            echo 'false' >> $CHANGED
          fi
  build:
    runs-on: ubuntu-latest
    if: ${{ env.CHANGED }} == 'true'
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get -y install shellcheck
    - name: Analysing the code with Shellcheck (errors)
      run: |
        shellcheck -e SC1091 --severity=error $(git ls-files -m '*.sh')
    - name: Analysing the code with Shellcheck (non-fatal)
      run: |
        shellcheck -e SC1091 $(git ls-files -m '*.sh') || true
