name: Shellcheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get -y install shellcheck
    - name: Analysing the code with Shellcheck (errors)
      run: |
        shellcheck -e SC1091 --neverity=error $(git ls-files '*.sh')
    - name: Analysing the code with Shellcheck (non-fatal)
      run: |
        shellcheck -e SC1091 --neverity=error $(git ls-files '*.sh') || true
