name: Shellcheck

on: [push]

jobs:
  check-modified:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for modified shell scripts
        id: check
        run: |
          if [ -n "$(git ls-files -m '*.sh')" ]; then
            echo "changed=true" >> $GITHUB_ENV
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_ENV
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  shellcheck:
    runs-on: ubuntu-latest
    needs: check-modified
    if: needs.check-modified.outputs.changed == 'true'

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get -y install shellcheck
      - name: Analysing the code with Shellcheck (errors)
        run: |
          shellcheck -e SC1091 --severity=error $(git ls-files -m '*.sh')
      - name: Analysing the code with Shellcheck (non-fatal)
        run: |
          shellcheck -e SC1091 $(git ls-files -m '*.sh') || true
